name: linshare_flutter_app
description: Linshare Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependency_overrides:
  # intl
  intl: 0.17.0

  # build_runner dependencies
  crypto: 3.0.0
  args: 2.0.0
  dart_style: 2.0.0
  analyzer: 1.4.0
  convert: 3.0.0
  petitparser: 4.1.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  data:
    path: data

  domain:
    path: domain

  # Http client
  dio: 4.0.0
  json_annotation: 4.0.1

  #get_it
  get_it: 7.1.3

  #  redux
  flutter_redux: 0.8.2

  # redux_thunk
  redux_thunk: 0.4.0

  #  either
  dartz: 0.10.0-nullsafety.1

  # shared_preferences
  shared_preferences: 2.0.5

  #rxdart
  rxdart: 0.26.0

  # device_info
  device_info: 2.0.0

  # file_picker
  file_picker: 3.0.1

  # flutter_uploader
  flutter_uploader: 1.2.1

  # flutter toast
  fluttertoast: 8.0.6

  # redux_logging
  redux_logging: 0.5.0

  # receive_sharing_intent
  receive_sharing_intent: 1.4.1

  # intl
  intl: 0.17.0
  intl_translation: 0.17.10+1

  # flutter_svg
  flutter_svg: 0.22.0

  # flutter_downloader
  flutter_downloader: 1.6.0

  #filesize
  filesize: 2.0.1

  # share
  share: 2.0.1

  # flutter_tags
  flutter_tags: 1.0.0-nullsafety.1

  # flutter_typeahead
  flutter_typeahead: 3.1.1

  # Mime type
  mime: 1.0.0

  # connectivity
  connectivity: 3.0.3

  # open_file
  open_file: 3.2.0
  # url_launcher
  url_launcher: 6.0.6

  # pin_code
  pin_code_fields: 7.2.0

  # local_auth
  local_auth: 1.1.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.2
  pedantic: 1.11.0
  permission_handler: 7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: 2.0.1
  json_serializable: 4.1.1
  test: 1.16.8
  mockito: 5.0.10
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
